### ISSUE TITLE
Error with Ruby 3

### ISSUE THREAD

**Issue by ryoung** [austinthecoder/t12n#1]
I'm getting an error with Ruby 3. 
I'm using the library like this:

```
class Issue
      WebApi.t12n.define_schema("Issue") do
        attrs(
          :id,
          :created_at,
          :updated_at,
          :number,
          :due_date,
          :reported_at,
          :summary,
          :description,
          :resolved_meter_variance,
          :resolved_secondary_meter_variance,
          :resolved_date_variance_in_days,
          :resolved_at,
          :closed_at
        )
    end
    .....
    associated_attrs(:custom_field, &:custom_fields)
end
```

Stack trace with error when class is loaded because of the associated_attrs line
```
lib/t12n/serializer.rb:13:in 'from_proc': Unexpected proc arity: -2 (T12n::ArgumentError)
lib/t12n/schema_builder.rb:38:in 'associated_attrs'
...
```

**Comment by ryoung** [comment]
Looks like I can just do:
`associated_attrs(:custom_field, nil, &:custom_fields)`

**Comment by ryoung** [comment]
Actually, that didn't work.

**Comment by austinthecoder** [comment]
Thanks for raising. I'll get tests running on Ruby 3 and see about getting it working.

**Comment by austinthecoder** [comment]
Nice, [testing on 3.0.1](https://github.com/austinthecoder/t12n/commit/b555f15eea7de61b5829528315f3b8bf55cec883) caught it: https://travis-ci.com/github/austinthecoder/t12n/jobs/505504565#L313

Looks like `Symbol#to_proc` returns a lambda Proc in Ruby 3. Should be a straightforward fix.
